export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Features } from "./Features";
export { default as HowItWorks } from "./HowItWorks";
export { default as About } from "./About";
export { default as Achievements } from "./Achievements";
export { default as Download } from "./Download";
export { default as Footer } from "./Footer";
export { default as Logo } from "./Logo";
